name: petology_web
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.0-271.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  conditional_builder_null_safety: ^0.0.6
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  carousel_slider: ^4.1.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1


flutter:


  uses-material-design: true

  assets:
     - assets/images/


fonts:
    - family: Arial
      fonts:
        - asset: fonts/ArialTh.ttf


